CREATE TABLE users(
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	display_name VARCHAR(20) NOT NULL DEFAULT 'ゲスト',
	email VARCHAR(254) UNIQUE NOT NULL,
	avatar_key VARCHAR(512) DEFAULT NULL,
	role VARCHAR NOT NULL CHECK (role IN ('user', 'admin')) DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
